apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: go-test-pipeline
spec:
  tasks:
    - name: my-task
      taskRef:
        resolver: git
        params:
        - name: url 
          value: https://github.com/dheerajodha/the-mentalist-quiz
        - name: revision
          value: "ui-tests"
        - name: pathInRepo
          value: integration-tests/task/test-task.yaml
